trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Pyhon 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  workingDirectory: libs/langchain
  displayName: 'Install dependencies'